# Generated by Django 5.1.6 on 2025-03-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_age_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age',
        ),
    ]
