# Generated by Django 5.1.6 on 2025-03-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 21, 10, 27, 5, 291192, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
